Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -18,18 +18,19 @@ jobs:
           chmod 600 ~/.ssh/github-actions
       - name: SSH into EC2 and deploy
         run: |
-         ssh -o StrictHostKeyChecking=no -i ~/.ssh/github-actions ubuntu@13.50.238.74 'sudo su -'
-            cd /var/www/html/svalbard || { echo "Error: Failed to change directory"; exit 1; }
-            sudo rm -rf .next || { echo "Error: Failed to remove .next directory"; exit 1; }
-            sudo rm -rf node_modules || { echo "Error: Failed to remove modules directory"; exit 1; }
-            sudo npm uninstall -g npm || { echo "Error: Failed to tell node directory"; exit 1; }
-            sudo apt update || { echo "Error: Failed to tell node directory"; exit 1; }
-            sudo apt install npm || { echo "Error: Failed to tell node directory"; exit 1; }
-            npm --version || { echo "Error: Failed to tell semver directory"; exit 1; }
-            export NODE_OPTIONS="--max-old-space-size=4096"
-            node -v || { echo "Error: Failed to install Node.js version 18.17.0"; exit 1; }
-            npm install || { echo "Error: Failed to install npm dependencies"; exit 1; }
-            npm run build || { echo "Error: Failed to build Next.js app"; exit 1; }
-            # pm2 start npm --name "svalbard" -- run start || { echo "Error: Failed to start PM2 process"; exit 1; }
-            # sudo systemctl restart nginx || { echo "Error: Failed to restart Nginx"; exit 1; }
-          EOF
+         ssh -o StrictHostKeyChecking=no -i ~/.ssh/github-actions ubuntu@13.50.238.74 << 'EOF'
+         sudo su -
+         cd /var/www/html/svalbard || { echo "Error: Failed to change directory"; exit 1; }
+         sudo rm -rf .next || { echo "Error: Failed to remove .next directory"; exit 1; }
+         sudo rm -rf node_modules || { echo "Error: Failed to remove modules directory"; exit 1; }
+         sudo npm uninstall -g npm || { echo "Error: Failed to tell node directory"; exit 1; }
+         sudo apt update || { echo "Error: Failed to tell node directory"; exit 1; }
+         sudo apt install npm || { echo "Error: Failed to tell node directory"; exit 1; }
+         npm --version || { echo "Error: Failed to tell semver directory"; exit 1; }
+         export NODE_OPTIONS="--max-old-space-size=4096"
+         node -v || { echo "Error: Failed to install Node.js version 18.17.0"; exit 1; }
+         npm install || { echo "Error: Failed to install npm dependencies"; exit 1; }
+         npm run build || { echo "Error: Failed to build Next.js app"; exit 1; }
+         # pm2 start npm --name "svalbard" -- run start || { echo "Error: Failed to start PM2 process"; exit 1; }
+         # sudo systemctl restart nginx || { echo "Error: Failed to restart Nginx"; exit 1; }
+         EOF
