Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,35 +1,35 @@
-# name: Deploy to EC2
+name: Deploy to EC2
 
-# on:
-#   push:
-#     branches:
-#       - main
+on:
+  push:
+    branches:
+      - main
 
-# jobs:
-#   deploy:
-#     runs-on: ubuntu-latest
-#     steps:
-#       - name: Checkout code
-#         uses: actions/checkout@v2
+jobs:
+  deploy:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-#       - name: Set up SSH
-#         run: |
-#           mkdir -p ~/.ssh
-#           echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github-actions
-#           chmod 600 ~/.ssh/github-actions
+      - name: Set up SSH
+        run: |
+          mkdir -p ~/.ssh
+          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github-actions
+          chmod 600 ~/.ssh/github-actions
 
-#       - name: SSH into EC2 and deploy
-#         run: |
-#           ssh -o StrictHostKeyChecking=no -i ~/.ssh/github-actions ubuntu@13.50.238.74 'bash -s' << 'EOF'
-#             cd /var/www/html/svalbard || { echo "Error: Failed to change directory"; exit 1; }
-#             rm -rf .next || { echo "Error: Failed to remove .next directory"; exit 1; }
-#             export NODE_OPTIONS="--max-old-space-size=4096"
-#             # Install Node.js version 18.17.0
-#             curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
-#             sudo apt-get install -y nodejs
-#             node -v || { echo "Error: Failed to install Node.js version 18.17.0"; exit 1; }
-#             npm install || { echo "Error: Failed to install npm dependencies"; exit 1; }
-#             npm run build || { echo "Error: Failed to build Next.js app"; exit 1; }
-#             pm2 start npm --name "svalbard" -- run start || { echo "Error: Failed to start PM2 process"; exit 1; }
-#             sudo systemctl restart nginx || { echo "Error: Failed to restart Nginx"; exit 1; }
-#           EOF
+      - name: SSH into EC2 and deploy
+        run: |
+          ssh -o StrictHostKeyChecking=no -i ~/.ssh/github-actions ubuntu@13.50.238.74 'bash -s' << 'EOF'
+            cd /var/www/html/svalbard || { echo "Error: Failed to change directory"; exit 1; }
+            # rm -rf .next || { echo "Error: Failed to remove .next directory"; exit 1; }
+            export NODE_OPTIONS="--max-old-space-size=4096"
+            # Install Node.js version 18.17.0
+            # curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
+            # sudo apt-get install -y nodejs
+            node -v || { echo "Error: Failed to install Node.js version 18.17.0"; exit 1; }
+            # npm install || { echo "Error: Failed to install npm dependencies"; exit 1; }
+            npm run build || { echo "Error: Failed to build Next.js app"; exit 1; }
+            # pm2 start npm --name "svalbard" -- run start || { echo "Error: Failed to start PM2 process"; exit 1; }
+            # sudo systemctl restart nginx || { echo "Error: Failed to restart Nginx"; exit 1; }
+          EOF
