Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -17,12 +17,15 @@ jobs:
           mkdir -p ~/.ssh
           echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github-actions
           chmod 600 ~/.ssh/github-actions
+
       - name: Setup Node.js
         uses: actions/setup-node@v3
         with:
           node-version: '18.17.0'
+
       - name: Verify Node.js installation
         run: node --version
+
       - name: SSH into EC2 and deploy
         run: |
           ssh -o StrictHostKeyChecking=no -i ~/.ssh/github-actions ubuntu@13.50.238.74 'bash -s' << 'EOF'
@@ -30,7 +33,8 @@ jobs:
             rm -rf .next || { echo "Error: Failed to remove .next directory"; exit 1; }
             rm -rf node_modules || { echo "Error: Failed to remove node_modules directory"; exit 1; }
             npm install || { echo "Error: Failed to install npm dependencies"; exit 1; }
-            NODE_OPTIONS="--max-old-space-size=4096" npm run build || { echo "Error: Failed to build Next.js app"; exit 1; }
+            export NODE_OPTIONS="--max-old-space-size=4096"
+            npm run build || { echo "Error: Failed to build Next.js app"; exit 1; }
             pm2 delete "svalbard" || { echo "Error: Failed to stop pm2"; exit 1; }
             pm2 start npm --name "svalbard" -- run start || { echo "Error: Failed to start PM2 process"; exit 1; }
             sudo systemctl restart nginx || { echo "Error: Failed to restart Nginx"; exit 1; }
